enum TokenType {
    LEFT_BRACE, RIGHT_BRACE, // (,),[,]
    BEGIN, END, DISPLAY, SCAN,// BEGIN CODE, END CODE
    SHARP, NEXT_LINE, AMPERSAND, ASSIGNMENT, // #, $, &, =
    INT, BOOL, CHAR, FLOAT,

    //ARITHMETIC OPERATORS
    LEFT_PARENTHESIS, RIGHT_PARENTHESIS, // (,)
    MULTIPLICATION, DIVISION, MODULO, // *, /, %
    ADDTION, SUBTRACTION, // +, -
    GREATER_THAN, LESSER_THAN, // >, <
    GREATER_EQUAL, LESSER_EQUAL, // >=, <=
    EQUAL, NOT_EQUAL, // ==, <>

    //LOGICAL OPERATORS
    AND, OR, NOT,

    //UNARY_OPERATOR
    POSITIVE_UNARY, NEGATIVE_UNARY,

    //CONDITIONAL
    IF, ELSE, ELSE_IF, END_IF, BEGIN_IF,
    WHILE, BEGIN_WHILE, END_WHILE,
    IDENTIFIER, STRING_LIT, INT_LIT, BOOL_LIT, FLOAT_LIT, CHAR_LIT,
    EOF, EOL, ERROR
}
